"""init

Revision ID: 3254e970e61a
Revises: 
Create Date: 2023-11-23 11:19:31.792974

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3254e970e61a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('registration_date', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('daily_bonus_step', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('daily_card_step', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('daily_affirmation_step', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('got_2h_autosending', sa.TIMESTAMP(), nullable=True),
    sa.Column('got_24h_autosending', sa.TIMESTAMP(), nullable=True),
    sa.Column('got_48h_autosending', sa.TIMESTAMP(), nullable=True),
    sa.Column('bf_state', sa.String(length=64), nullable=True),
    sa.Column('bf_22nov', sa.TIMESTAMP(), nullable=True),
    sa.Column('bf_2_22nov', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
