"""init

Revision ID: 659c94cbf842
Revises: 3254e970e61a
Create Date: 2023-11-23 11:24:22.712769

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '659c94cbf842'
down_revision = '3254e970e61a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('files',
    sa.Column('path', sa.String(length=256), nullable=False),
    sa.Column('telegram_id', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('path')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('files')
    # ### end Alembic commands ###
