"""add 30_april_sending

Revision ID: f3f6a19b67ea
Revises: ebfb8ed73122
Create Date: 2024-04-30 15:17:56.596491

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f3f6a19b67ea'
down_revision = 'ebfb8ed73122'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('sending_30_april', sa.TIMESTAMP(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'sending_30_april')
    # ### end Alembic commands ###
