"""init

Revision ID: 320ce2a5a0c4
Revises: 98c8d452dfaa
Create Date: 2024-03-25 05:07:07.649193

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '320ce2a5a0c4'
down_revision = '98c8d452dfaa'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
