"""init

Revision ID: 95010385744f
Revises: adec750e35be
Create Date: 2024-04-04 06:40:00.100428

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95010385744f'
down_revision = 'adec750e35be'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('sending_4_april', sa.TIMESTAMP(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'sending_4_april')
    # ### end Alembic commands ###
