"""empty message

Revision ID: ebfb8ed73122
Revises: 761c02dc1165
Create Date: 2024-04-24 14:03:02.456503

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ebfb8ed73122'
down_revision = '761c02dc1165'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('sending_24_april', sa.TIMESTAMP(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'sending_24_april')
    # ### end Alembic commands ###
